AllCops:
  TargetRubyVersion: 2.2

  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'script/**/*'

Rails:
  Enabled: true


## Metrics

# Maximum class length of 100 lines
Metrics/ClassLength:
  Max: 100

# Maximum module length of 100 lines
Metrics/ModuleLength:
  Max: 100

# Maximum method length of 10 lines
Metrics/MethodLength:
  Max: 10

# 100 character width
Metrics/LineLength:
  Max: 100


## Style

# Align hashes neatly
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Allow UTF-8 chars in comments
Style/AsciiComments:
  Enabled: false

# We don't write documentation here :D
Style/Documentation:
  Enabled: false

# Dave likes his dots trailing
Style/DotPosition:
  EnforcedStyle: trailing

# Empty lines between methods unless they are one liners
Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Allow extra spacing for alignment
Style/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: false

# More flexible array alignment
Style/IndentArray:
  EnforcedStyle: consistent

# More flexible hash alignment
Style/IndentHash:
  EnforcedStyle: consistent

# Double quotes for "strings"
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Single quotes within interpolated strings: "hello#{hash['there']}"
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
